### PR TITLE
added keyboard controller na kub 

### PR DESCRIPTION
**Pull request by ongss**

### CODE REVIEW

**Comment by phizaz** [comment]
Please conform with the existing code base which doesn't use semicolons

On Nov 8, 2017 2:48 PM, "ongEiEi" <notifications@github.com> wrote:

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/phizaz/mouse-server/pull/1
Commit Summary

   - add keyboard controller
   - debug

File Changes

   - *M* server.js
   <https://github.com/phizaz/mouse-server/pull/1/files#diff-0> (80)

Patch Links:

   - https://github.com/phizaz/mouse-server/pull/1.patch
   - https://github.com/phizaz/mouse-server/pull/1.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/phizaz/mouse-server/pull/1>, or mute the thread

**Comment by konpatp** [comment]
Please conform with the existing code base by removing all the semicolons

**Comment by ongss** [comment]
I have remove all semicolons , added more key and added functions keyHold in keyboard controller . Is it ok?

**Review by konpatp — COMMENTED** [review]
I want you to justify the need of "keyHold-*" functions, before I decide to add it. 

By the way, it is quite prone to race-condition, requesting this many times. Might this make it harder for people to debug ?

**Review by konpatp — COMMENTED** [review]
Again, I want you to justify the for this key up and down.

**Comment by ongss** [comment]
If I want my game character move forward for 2 meter then I just use key-tab 100 times(may be). I think it gonna make my game character lacking when it move that why I added functions keyHold-* and key up-down.

**Comment by konpatp** [comment]
As I understand the code, the **hold** function needs a user to specify "holding time" before hand ... which has a very *specific* use ... it makes more sense to create a function **toggle** in such a way that when a user pushes down it toggles down ... when a user releases it toggles up, like keydown and up.

If you change it to .. **toggle** I can understand a way to profit other people.

**Comment by ongss** [comment]
I have change all hold functions to toggle functions already. Is this code okay now?

**Review by konpatp — COMMENTED** [review]
Please update the naming convention from "toggle" to "up  and down"

**Pull request merged**
